### ISSUE TITLE
Improve difficult terrain rules

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/fop-game#30]
## What problem does the current design create?

Rounding down or reducing by one causes strange edge cases with forced movement.

## What solution would you like?

Forced movement reduced by half, rounded up.

## What alternative(s) have you considered?

No effect on forced movement.

**Comment by plof27** [comment]
It has weird edges with regular movement as well. Difficult terrain is applied if you're leaving a DT tile, right?

**Comment by alice-i-cecile** [comment]
Fixed in https://github.com/Leafwing-Studios/fop-game/commit/4c3e85154e253330fad34cb30dacca256f66abc7.

**Comment by alice-i-cecile** [comment]
Nope, still broken. If you move into difficult terrain while adjacent, you lose 1 tile of movement.

Storing "tiles of movement" or some other form of cross-action state is the only solution.

**Comment by alice-i-cecile** [comment]
Done.
